
'c';

z + x + a * b ^ c + y;

a * b ^ c;

a + b + c + d;

- - mystruct.myval ^ b;

f(c(),a + b,g(a + b + c + d),h()+p(s));

(a+b+c)*d;

var s : String = "ciao";

while n + 1 < 10 + 3 * 2 {
    var x : X = y = z;
    print("ciao");
    n = n + 1;
}

a = func_that_returns_a_reference() = #c = 6;

while n < 10 print();

if n < 10 {
    print("less then ten");
} else if n > 10 {
    print("more then ten");
} else {
    print("exactly ten");
}

a + b * c ^ d * e + f;