var result : String;

true;
false;
"ciao";
'a';
123;
1.2;

var flag : Bool = true;

struct Segment {
    struct Point {
        x : Float;
        y : Float;
    }
    a : Point;
    b : Point;
}

var follia : Bool;

func plot_fuction(){
    
    var s : S;

    struct Point {
        x : Float;
        y : Float;
    } 

    var s : S;
    

    func plot_point(){
        var p : Point;
    }


    var s : S;
    
}